name: Build Autokey pages
on: [push]
jobs:
  sphinx-build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt install git python3-tk -y
          pip install sphinx recommonmark sphinx-rtd-theme sphinx-epytext
          git clone https://github.com/autokey/autokey
          cd autokey
          pip install .
          cd ..
          mkdir docs
          ls
          sphinx-build -a -E -b html ./autokey/doc/sphinx ./docs
      
