name: Build Autokey pages
on: [push]
jobs:
  sphinx-build:
    runs-on: ubuntu-latest
    steps:
      - run: apt install git -y
      - run: pip install sphinx recommonmark sphinx-rtd-theme sphinx-epytext
      - run: git clone https://github.com/autokey/autokey
      - run: cd autokey
      - run: pip install .
      - run: cd ..
      - run: sphinx-build -a -E -b html ./autokey/doc/sphinx
      
